name: .NET Core

on: [push]

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🔨 Use .NET 6.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Restore with dotnet
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build -c Release --no-restore
      - name: Test with dotnet
        run: dotnet test 
